// <auto-generated />
using System;
using FitMe.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitMe.API.Migrations
{
    [DbContext(typeof(FitMeDbContext))]
    [Migration("20251130044610_InitialClean")]
    partial class InitialClean
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramEnroll", b =>
                {
                    b.Property<Guid>("ProgramEnrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("program_enroll_id");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workout_program_id");

                    b.HasKey("ProgramEnrollId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("tbl_program_enroll", (string)null);
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.ToTable("tbl_role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Admin can control dashboard",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Coach can make new program workout",
                            Name = "Coach"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Member can follow programworkout",
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasColumnName("height");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<long?>("Otp")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("tbl_user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Age = 25,
                            CreatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9343),
                            Email = "admin1@gmail.com",
                            Gender = "Male",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "12345",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9358),
                            Weight = 65.0
                        },
                        new
                        {
                            UserId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Age = 30,
                            CreatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9372),
                            Email = "coach1@gmail.com",
                            Gender = "Male",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "123456",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9373),
                            Weight = 65.0
                        },
                        new
                        {
                            UserId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Age = 30,
                            CreatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9377),
                            Email = "coach2@gmail.com",
                            Gender = "Female",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "123456",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9378),
                            Weight = 65.0
                        },
                        new
                        {
                            UserId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Age = 30,
                            CreatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9381),
                            Email = "member1@gmail.com",
                            Gender = "Female",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "123",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9382),
                            Weight = 65.0
                        },
                        new
                        {
                            UserId = new Guid("12300000-0000-0000-0000-000000000003"),
                            Age = 30,
                            CreatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9385),
                            Email = "coach3@gmail.com",
                            Gender = "Female",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "123",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9386),
                            Weight = 65.0
                        },
                        new
                        {
                            UserId = new Guid("12345000-0000-0000-0000-000000000003"),
                            Age = 30,
                            CreatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9394),
                            Email = "coach4@gmail.com",
                            Gender = "Female",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "1234",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 424, DateTimeKind.Local).AddTicks(9395),
                            Weight = 65.0
                        });
                });

            modelBuilder.Entity("WorkoutProgram", b =>
                {
                    b.Property<Guid>("WorkoutProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workout_program_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("difficulty");

                    b.Property<int>("DurationWeeks")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("duration_weeks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("WorkoutProgramId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_workout_program", (string)null);

                    b.HasData(
                        new
                        {
                            WorkoutProgramId = new Guid("12300000-1234-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 428, DateTimeKind.Local).AddTicks(9128),
                            Description = "Perlu mengikuti step by step",
                            Difficulty = "Intermediate",
                            DurationWeeks = 1,
                            Status = "Active",
                            Title = "Bulking",
                            UpdatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 428, DateTimeKind.Local).AddTicks(9141),
                            UserId = new Guid("12300000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            WorkoutProgramId = new Guid("12345000-1234-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 428, DateTimeKind.Local).AddTicks(9148),
                            Description = "Perlu mengikuti step by step",
                            Difficulty = "Intermediate",
                            DurationWeeks = 1,
                            Status = "Pending",
                            Title = "LegDay",
                            UpdatedAt = new DateTime(2025, 11, 30, 11, 46, 8, 428, DateTimeKind.Local).AddTicks(9149),
                            UserId = new Guid("12300000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("WorkoutSession", b =>
                {
                    b.Property<Guid>("WorkoutSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workout_session_id");

                    b.Property<string>("DurationMinutes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("instructions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("video_url");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workout_program_id");

                    b.HasKey("WorkoutSessionId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("tbl_workout_session", (string)null);

                    b.HasData(
                        new
                        {
                            WorkoutSessionId = new Guid("267c20e5-e1de-48a9-888b-a946e969bad9"),
                            DurationMinutes = "20:00",
                            Instructions = "Dalam pembelajaran ini yang harus dipersiapkan adalah bla bla bla",
                            Title = "Step 01 Bulk",
                            VideoUrl = "https/test",
                            WorkoutProgramId = new Guid("12300000-1234-0000-0000-000000000003")
                        },
                        new
                        {
                            WorkoutSessionId = new Guid("e74f8687-e1da-4808-93ef-c794bad5e278"),
                            DurationMinutes = "20:00",
                            Instructions = "Dalam pembelajaran ini yang harus dipersiapkan adalah bebebe",
                            Title = "Step 02 Bulk",
                            VideoUrl = "https/test",
                            WorkoutProgramId = new Guid("12300000-1234-0000-0000-000000000003")
                        },
                        new
                        {
                            WorkoutSessionId = new Guid("caafa49e-1e8a-4e27-bb9b-927b6006fc16"),
                            DurationMinutes = "20:00",
                            Instructions = "Dalam pembelajaran ini yang harus dipersiapkan adalah bobobo",
                            Title = "Step 01 Bulk",
                            VideoUrl = "https/test",
                            WorkoutProgramId = new Guid("12300000-1234-0000-0000-000000000003")
                        },
                        new
                        {
                            WorkoutSessionId = new Guid("c8cdc202-c9e6-43d0-8dbc-891595857455"),
                            DurationMinutes = "20:00",
                            Instructions = "Dalam pembelajaran ini..",
                            Title = "Step 01 Leg",
                            VideoUrl = "https/test",
                            WorkoutProgramId = new Guid("12345000-1234-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("ProgramEnroll", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("ProgramEnroll")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkoutProgram", "WorkoutProgram")
                        .WithMany("ProgramEnroll")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorkoutProgram", b =>
                {
                    b.HasOne("User", null)
                        .WithMany("WorkoutProgram")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutSession", b =>
                {
                    b.HasOne("WorkoutProgram", "WorkoutProgram")
                        .WithMany("WorkoutSession")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("ProgramEnroll");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("WorkoutProgram", b =>
                {
                    b.Navigation("ProgramEnroll");

                    b.Navigation("WorkoutSession");
                });
#pragma warning restore 612, 618
        }
    }
}
