// <auto-generated />
using System;
using FitMe.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitMe.API.Migrations
{
    [DbContext(typeof(FitMeDbContext))]
    [Migration("20251128031440_Revisi")]
    partial class Revisi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProgramEnroll", b =>
                {
                    b.Property<Guid>("ProgramEnrollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("program_enroll_id");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workout_program_id");

                    b.HasKey("ProgramEnrollId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("tbl_program_enroll", (string)null);
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.ToTable("tbl_role", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Admin can control dashboard",
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Coach can make new program workout",
                            Name = "Coach"
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Member can follow programworkout",
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<double>("Height")
                        .HasColumnType("float")
                        .HasColumnName("height");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<long?>("Otp")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float")
                        .HasColumnName("weight");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("tbl_user", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("949561eb-b7cd-4244-85c3-6c9c127198cd"),
                            Age = 25,
                            CreatedAt = new DateTime(2025, 11, 28, 10, 14, 37, 742, DateTimeKind.Local).AddTicks(3503),
                            Email = "admin1@gmail.com",
                            Gender = "Male",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "12345",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTime(2025, 11, 28, 10, 14, 37, 742, DateTimeKind.Local).AddTicks(3520),
                            Weight = 65.0
                        },
                        new
                        {
                            UserId = new Guid("a99b02a2-cc2b-4328-8d2d-85fb0c2df930"),
                            Age = 30,
                            CreatedAt = new DateTime(2025, 11, 28, 10, 14, 37, 742, DateTimeKind.Local).AddTicks(3527),
                            Email = "coach1@gmail.com",
                            Gender = "Male",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "123456",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 11, 28, 10, 14, 37, 742, DateTimeKind.Local).AddTicks(3528),
                            Weight = 65.0
                        },
                        new
                        {
                            UserId = new Guid("55b6322f-7068-4cb0-a599-4ddeb95df7dc"),
                            Age = 30,
                            CreatedAt = new DateTime(2025, 11, 28, 10, 14, 37, 742, DateTimeKind.Local).AddTicks(3552),
                            Email = "coach2@gmail.com",
                            Gender = "Female",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "123456",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTime(2025, 11, 28, 10, 14, 37, 742, DateTimeKind.Local).AddTicks(3553),
                            Weight = 65.0
                        },
                        new
                        {
                            UserId = new Guid("11263469-1d43-4b9c-9e5b-89492c9560e3"),
                            Age = 30,
                            CreatedAt = new DateTime(2025, 11, 28, 10, 14, 37, 742, DateTimeKind.Local).AddTicks(3560),
                            Email = "member1@gmail.com",
                            Gender = "Female",
                            Height = 175.0,
                            IsUsed = false,
                            Password = "123",
                            RoleId = new Guid("10000000-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTime(2025, 11, 28, 10, 14, 37, 742, DateTimeKind.Local).AddTicks(3561),
                            Weight = 65.0
                        });
                });

            modelBuilder.Entity("WorkoutProgram", b =>
                {
                    b.Property<Guid>("WorkoutProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workout_program_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("difficulty");

                    b.Property<int>("DurationWeeks")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("duration_weeks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("WorkoutProgramId");

                    b.HasIndex("UserId");

                    b.ToTable("tbl_workout_program", (string)null);
                });

            modelBuilder.Entity("WorkoutSession", b =>
                {
                    b.Property<Guid>("WorkoutSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workout_session_id");

                    b.Property<string>("DurationMinutes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("instructions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("video_url");

                    b.Property<Guid>("WorkoutProgramId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("workout_program_id");

                    b.HasKey("WorkoutSessionId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("tbl_workout_session", (string)null);
                });

            modelBuilder.Entity("ProgramEnroll", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("ProgramEnroll")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkoutProgram", "WorkoutProgram")
                        .WithMany("ProgramEnroll")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WorkoutProgram", b =>
                {
                    b.HasOne("User", null)
                        .WithMany("WorkoutProgram")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutSession", b =>
                {
                    b.HasOne("WorkoutProgram", "WorkoutProgram")
                        .WithMany("WorkoutSession")
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("ProgramEnroll");

                    b.Navigation("WorkoutProgram");
                });

            modelBuilder.Entity("WorkoutProgram", b =>
                {
                    b.Navigation("ProgramEnroll");

                    b.Navigation("WorkoutSession");
                });
#pragma warning restore 612, 618
        }
    }
}
